### ISSUE TITLE
Cannot compile on windows-11 rust 1.76

### ISSUE THREAD

**Issue by yavorski** [kkysen/mklink#1]
Here is the log: 

```rust
error[E0308]: mismatched types
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals.rs:78:32
    |
78  |     helpers::set_reparse_point(file.as_raw_handle(), rdb, u32::from(in_buffer_size))
    |     -------------------------- ^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
    |     |
    |     arguments to this function are incorrect
    |
    = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
   --> /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ffi\mod.rs:209:1
note: `winapi::ctypes::c_void` is defined in crate `winapi`
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
    |
38  |     pub enum c_void {}
    |     ^^^^^^^^^^^^^^^
note: function defined here
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals\helpers.rs:130:8
    |
130 | pub fn set_reparse_point(handle: HANDLE, rdb: *mut ReparseDataBuffer, len: u32) -> io::Result<()> {
    |        ^^^^^^^^^^^^^^^^^ --------------

error[E0308]: mismatched types
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals.rs:83:35
    |
83  |     helpers::delete_reparse_point(file.as_raw_handle())
    |     ----------------------------- ^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
    |     |
    |     arguments to this function are incorrect
    |
    = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
   --> /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ffi\mod.rs:209:1
note: `winapi::ctypes::c_void` is defined in crate `winapi`
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
    |
38  |     pub enum c_void {}
    |     ^^^^^^^^^^^^^^^
note: function defined here
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals\helpers.rs:151:8
    |
151 | pub fn delete_reparse_point(handle: HANDLE) -> io::Result<()> {
    |        ^^^^^^^^^^^^^^^^^^^^ --------------

error[E0308]: mismatched types
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals.rs:93:47
    |
93  |     let rdb = helpers::get_reparse_data_point(file.as_raw_handle(), &mut data)?;
    |               ------------------------------- ^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
    |               |
    |               arguments to this function are incorrect
    |
    = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
   --> /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ffi\mod.rs:209:1
note: `winapi::ctypes::c_void` is defined in crate `winapi`
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
    |
38  |     pub enum c_void {}
    |     ^^^^^^^^^^^^^^^
note: function defined here
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals\helpers.rs:106:8
    |
106 | pub fn get_reparse_data_point<'a>(handle: HANDLE, data: &'a mut [u8]) -> io::Result<&'a ReparseDataBuffer> {
    |        ^^^^^^^^^^^^^^^^^^^^^^     --------------

error[E0308]: mismatched types
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals.rs:104:47
    |
104 |     let rdb = helpers::get_reparse_data_point(file.as_raw_handle(), &mut data)?;
    |               ------------------------------- ^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
    |               |
    |               arguments to this function are incorrect
    |
    = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
   --> /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ffi\mod.rs:209:1
note: `winapi::ctypes::c_void` is defined in crate `winapi`
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
    |
38  |     pub enum c_void {}
    |     ^^^^^^^^^^^^^^^
note: function defined here
   --> C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\junction-0.1.5\src\internals\helpers.rs:106:8
    |
106 | pub fn get_reparse_data_point<'a>(handle: HANDLE, data: &'a mut [u8]) -> io::Result<&'a ReparseDataBuffer> {
    |        ^^^^^^^^^^^^^^^^^^^^^^     --------------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `junction` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mklink v0.1.0 (C:\dev\open-sos\mklink)`, intermediate artifacts can be found at `C:\dev\open-sos\mklink\target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
